### ISSUE TITLE
build doesn't finish

### ISSUE THREAD

**Issue by peerbolte** [danibram/mocker-data-generator#1]
First of all, thanks much for building this data generator. I'm using it to populate my mongodb to stress test aggregates on large amount of documents. 

When I generate large amount of objects, the application doesn't finish running. When i generate smaller chunks and run the application multiple times, all goes well. Is there a possible issue with larger object arrays? Maybe something with node memory limits / node array memory limit?

Thanks much

**Comment by peerbolte** [comment]
Ok the runtime increased exponentially. 
1000 objects had a runtime of 47 seconds. 
10000 objects had a runtime of 1026 seconds.

**Comment by danibram** [comment]
Hi!Maybe in the future i will add a progress bar, because right now sometimes you dont know if the process are doing or not.
You really generate a big amopunt of data, in the past, posts like [this](http://prestonparry.com/articles/IncreaseNodeJSMemorySize/) helps me to do big migrations in mongo. Im happy that you resolve your issue.

**Comment by danibram** [comment]
I also release the 1.0.3 version, and i review the code and change the for loop of the iterator by a map, this should give more speed.
