### ISSUE TITLE
casualjs leads to build error

### ISSUE THREAD

**Issue by Sshnyari** [danibram/mocker-data-generator#12]
is there a way to make casualjs optional ?
It doesn't work in a browser.
casualjs-browserify works though (see issue: https://github.com/boo1ean/casual/issues/20)

It is true that generating massive mock data in a client app isn't optimal, but it works very well for smaller test sets

**Comment by danibram** [comment]
Hi! First of all thanks for the help of improving this module, yep you are right, i have multiple option:
- make builds with casual and without it
- remove definitely from the module (this will be risk the purpose of the module)
- Use this fork [casual-browserify](https://github.com/Klowner/casual-browserify)

I think the best solution is to use the fork temporarily, because of the purpose of this module, i published right now the version 2.0.2 with that change, tell me if it is fixed
Thanks

**Comment by Sshnyari** [comment]
Yep, that solved it. Thanks
